name: Publish to PyPI (OIDC)

on:
  release:
    types: [published]  # Trigger when a GitHub release is published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       # Required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI (trusted publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
